export const MEMBERS_DATA = [
  {
    id: 1,
    name: 'Amara Diallo',
    role: 'ML Engineer',
    location: 'Dakar, Senegal',
    bio: 'Building AI solutions for healthcare in West Africa. Passionate about making ML accessible to everyone.',
    skills: ['Python', 'TensorFlow', 'PyTorch', 'FastAPI'],
    github: 'amaradiallo',
    linkedin: 'amara-diallo',
    twitter: 'amaradiallo_ai',
    created_at: '2026-01-01T00:00:00',
  },
  {
    id: 2,
    name: 'Kwame Mensah',
    role: 'Full Stack Developer',
    location: 'Accra, Ghana',
    bio: 'Founder of two startups. Love building products that solve real African problems with elegant code.',
    skills: ['React', 'Node.js', 'PostgreSQL', 'Docker'],
    github: 'kwamemensah',
    linkedin: 'kwame-mensah',
    twitter: null,
    created_at: '2026-01-02T00:00:00',
  },
  {
    id: 3,
    name: 'Fatima Al-Rashid',
    role: 'AI Researcher',
    location: 'Casablanca, Morocco',
    bio: 'Researching NLP for low-resource African languages. PhD candidate at Mohammed V University.',
    skills: ['NLP', 'Transformers', 'Python', 'HuggingFace'],
    github: 'fatimaalrashid',
    linkedin: null,
    twitter: 'fatima_nlp',
    created_at: '2026-01-03T00:00:00',
  },
  {
    id: 4,
    name: 'Chidi Okonkwo',
    role: 'Startup Founder',
    location: 'Lagos, Nigeria',
    bio: 'Serial entrepreneur building the future of fintech in Africa. YC Alum W23. Previously Paystack.',
    skills: ['Product', 'Fintech', 'Strategy', 'Fundraising'],
    github: 'chidiokonkwo',
    linkedin: 'chidi-okonkwo',
    twitter: 'chidiokonkwo',
    created_at: '2026-01-04T00:00:00',
  },
  {
    id: 5,
    name: 'Aisha Kamara',
    role: 'Data Scientist',
    location: 'Kigali, Rwanda',
    bio: 'Using data to drive development policy across East Africa. World Bank consultant and open data advocate.',
    skills: ['Python', 'R', 'SQL', 'Tableau', 'Statistics'],
    github: 'aishakamara',
    linkedin: 'aisha-kamara',
    twitter: null,
    created_at: '2026-01-05T00:00:00',
  },
  {
    id: 6,
    name: 'Tendai Moyo',
    role: 'DevOps Engineer',
    location: 'Harare, Zimbabwe',
    bio: 'Cloud infrastructure specialist helping African startups scale reliably. AWS Solutions Architect certified.',
    skills: ['AWS', 'Kubernetes', 'Terraform', 'CI/CD'],
    github: 'tendaimoyo',
    linkedin: 'tendai-moyo',
    twitter: 'tendai_devops',
    created_at: '2026-01-06T00:00:00',
  },
  {
    id: 7,
    name: 'Nadia Osei',
    role: 'UX Designer',
    location: 'Accra, Ghana',
    bio: 'Designing human-centered products for African users. Previously at Jumia and Paystack. Design systems nerd.',
    skills: ['Figma', 'Design Systems', 'User Research', 'Prototyping'],
    github: null,
    linkedin: 'nadia-osei',
    twitter: 'nadia_designs',
    created_at: '2026-01-07T00:00:00',
  },
  {
    id: 8,
    name: 'Ibrahim Touré',
    role: 'Backend Engineer',
    location: 'Bamako, Mali',
    bio: 'Distributed systems engineer building resilient infrastructure for low-connectivity environments across the Sahel.',
    skills: ['Go', 'Rust', 'PostgreSQL', 'Redis', 'gRPC'],
    github: 'ibrahimtoure',
    linkedin: 'ibrahim-toure',
    twitter: null,
    created_at: '2026-01-08T00:00:00',
  },
];

export const PROJECTS_DATA = [
  {
    id: 1,
    title: 'CropSense',
    description: 'AI-powered crop disease detection using smartphone cameras. Helps smallholder farmers identify plant diseases early and receive treatment recommendations in their local language.',
    category: 'AI/ML',
    tech_stack: ['Python', 'TensorFlow', 'React Native', 'FastAPI'],
    github_url: 'github.com/example/cropsense',
    demo_url: null,
    author_id: 1,
    author_name: 'Amara Diallo',
    created_at: '2026-01-01T00:00:00',
  },
  {
    id: 2,
    title: 'AfriPay',
    description: 'Cross-border payment infrastructure enabling instant, low-cost transactions across 54 African countries using blockchain technology and local mobile money integrations.',
    category: 'Fintech',
    tech_stack: ['Solidity', 'React', 'Node.js', 'Web3.js'],
    github_url: 'github.com/example/afripay',
    demo_url: 'afripay.demo',
    author_id: 4,
    author_name: 'Chidi Okonkwo',
    created_at: '2026-01-02T00:00:00',
  },
  {
    id: 3,
    title: 'TunaHealth',
    description: 'AI health diagnostic assistant trained on African disease patterns. Provides triage recommendations in 12 local languages via SMS and WhatsApp.',
    category: 'HealthTech',
    tech_stack: ['Python', 'NLP', 'React', 'PostgreSQL'],
    github_url: 'github.com/example/tunahealth',
    demo_url: null,
    author_id: 3,
    author_name: 'Fatima Al-Rashid',
    created_at: '2026-01-03T00:00:00',
  },
  {
    id: 4,
    title: 'EduBot',
    description: 'Adaptive learning platform powered by AI that personalizes education for students in resource-constrained schools. Works offline and syncs when connected.',
    category: 'EdTech',
    tech_stack: ['Python', 'React', 'Node.js', 'MongoDB'],
    github_url: 'github.com/example/edubot',
    demo_url: 'edubot.demo',
    author_id: 2,
    author_name: 'Kwame Mensah',
    created_at: '2026-01-04T00:00:00',
  },
  {
    id: 5,
    title: 'JuaData',
    description: 'Open dataset platform aggregating African economic, climate, and social data for researchers and policy makers. 500+ curated datasets.',
    category: 'Data',
    tech_stack: ['Python', 'PostgreSQL', 'FastAPI', 'React', 'D3.js'],
    github_url: 'github.com/example/juadata',
    demo_url: 'juadata.demo',
    author_id: 5,
    author_name: 'Aisha Kamara',
    created_at: '2026-01-05T00:00:00',
  },
  {
    id: 6,
    title: 'SafeRoute',
    description: 'Real-time urban safety mapping using crowdsourced incident reports and ML to suggest safer routes in African cities. Currently live in Lagos and Nairobi.',
    category: 'AI/ML',
    tech_stack: ['Python', 'React Native', 'Node.js', 'Maps API'],
    github_url: 'github.com/example/saferoute',
    demo_url: null,
    author_id: 1,
    author_name: 'Amara Diallo',
    created_at: '2026-01-06T00:00:00',
  },
  {
    id: 7,
    title: 'KuberAfrica',
    description: 'Managed Kubernetes platform optimised for African cloud providers with automatic failover for unreliable connectivity and bandwidth-aware scheduling.',
    category: 'DevOps',
    tech_stack: ['Go', 'Kubernetes', 'Terraform', 'Prometheus'],
    github_url: 'github.com/example/kuberafrica',
    demo_url: null,
    author_id: 6,
    author_name: 'Tendai Moyo',
    created_at: '2026-01-07T00:00:00',
  },
  {
    id: 8,
    title: 'AfriLang',
    description: 'Large language model pre-trained on 25 African languages. Open source, fine-tunable for downstream NLP tasks including translation, classification, and summarisation.',
    category: 'AI/ML',
    tech_stack: ['Python', 'PyTorch', 'Transformers', 'CUDA'],
    github_url: 'github.com/example/afrilang',
    demo_url: null,
    author_id: 3,
    author_name: 'Fatima Al-Rashid',
    created_at: '2026-01-08T00:00:00',
  },
];
